// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOpH3IIu45Hqmp3EG483K6QL-QXg0wSaw',
    appId: '1:237052702780:web:ed8cc943ef5126989a9339',
    messagingSenderId: '237052702780',
    projectId: 'chat-app-demo-6519d',
    authDomain: 'chat-app-demo-6519d.firebaseapp.com',
    storageBucket: 'chat-app-demo-6519d.firebasestorage.app',
    measurementId: 'G-4GT7PRYQ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWoOX5K_FE3fmVekWGdA_UMW8ab0fVxXA',
    appId: '1:237052702780:android:c4a49028870ba94c9a9339',
    messagingSenderId: '237052702780',
    projectId: 'chat-app-demo-6519d',
    storageBucket: 'chat-app-demo-6519d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlEkYAFe6ImevSzkMBqthsnTPQN5biBE',
    appId: '1:237052702780:ios:122c2ef382d8a5109a9339',
    messagingSenderId: '237052702780',
    projectId: 'chat-app-demo-6519d',
    storageBucket: 'chat-app-demo-6519d.firebasestorage.app',
    iosClientId: '237052702780-linrnrnj96s9oqc9m78cthp913ct5m33.apps.googleusercontent.com',
    iosBundleId: 'com.duytq.flutterchatdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlEkYAFe6ImevSzkMBqthsnTPQN5biBE',
    appId: '1:237052702780:ios:b023a0bc55ffd2fe9a9339',
    messagingSenderId: '237052702780',
    projectId: 'chat-app-demo-6519d',
    storageBucket: 'chat-app-demo-6519d.firebasestorage.app',
    iosClientId: '237052702780-ks4ufarbt1ugkkf9q015hevhmd06tgcp.apps.googleusercontent.com',
    iosBundleId: 'com.dfa.flutterchatdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOpH3IIu45Hqmp3EG483K6QL-QXg0wSaw',
    appId: '1:237052702780:web:d246a28b440900b59a9339',
    messagingSenderId: '237052702780',
    projectId: 'chat-app-demo-6519d',
    authDomain: 'chat-app-demo-6519d.firebaseapp.com',
    storageBucket: 'chat-app-demo-6519d.firebasestorage.app',
    measurementId: 'G-VEJC2JT891',
  );
}
